# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  confidential:

services:

  orderer.sunmi.com:
    extends:
      file:  base/docker-compose-base.yaml
      service: orderer.sunmi.com
    container_name: orderer.sunmi.com
    networks:
      - confidential

  peer0.farmer.com:
    container_name: peer0.farmer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.farmer.com
    networks:
      - confidential

  peer0.shipper.com:
    container_name: peer0.shipper.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.shipper.com
    networks:
      - confidential


  peer0.distributor.com:
   container_name: peer0.distributor.com
   extends:
     file:  base/docker-compose-base.yaml
     service: peer0.distributor.com
   networks:
     - confidential



  peer0.wholesaler.com:
   container_name: peer0.wholesaler.com
   extends:
     file:  base/docker-compose-base.yaml
     service: peer0.wholesaler.com
   networks:
     - confidential



  peer0.retailer.com:
   container_name: peer0.retailer.com
   extends:
     file:  base/docker-compose-base.yaml
     service: peer0.retailer.com
   networks:
     - confidential






  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.farmer.com:7051
      - CORE_PEER_LOCALMSPID=FarmerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/farmer.com/peers/peer0.farmer.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/farmer.com/peers/peer0.farmer.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/farmer.com/peers/peer0.farmer.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/farmer.com/users/Admin@farmer.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.sunmi.com
      - peer0.farmer.com
      - peer0.shipper.com
      - peer0.distributor.com
      - peer0.wholesaler.com
      - peer0.retailer.com
    networks:
      - confidential
