version: '2'

networks:
  confidential:

services:

  quantumCounchDB:
    container_name: quantumCounchDB
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    volumes:
      - ${DATA_PATH}/Peer/entanglement.quantum/couch0:/opt/couchdb/data
    ports:
      - "10984:5984"
    networks:
      - confidential

  peer0.entanglement.quantum.com:
    container_name: peer0.entanglement.quantum.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.entanglement.quantum.com
      - CORE_PEER_ADDRESS=peer0.entanglement.quantum.com:7051
#      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.farmer.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.entanglement.quantum.com:7051
      - CORE_PEER_LOCALMSPID=OrgQuantumMSP

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=quantumCounchDB:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-new-org/peerOrganizations/entanglement.quantum.com/peers/peer0.entanglement.quantum.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-new-org/peerOrganizations/entanglement.quantum.com/peers/peer0.entanglement.quantum.com/tls:/etc/hyperledger/fabric/tls
      - ${DATA_PATH}/Peer/entanglement.quantum/peer0:/var/hyperledger/production/
    ports:
      - 12051:7051
      - 12053:7053
    networks:
      - confidential
    depends_on:
      - quantumCounchDB